### ISSUE TITLE
Update sample to use Swift 3 

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#11]
Not sure if this is still an issue.

Steps to repro
1. Download the sample - http://developer.couchbase.com/documentation/mobile/1.3/develop/training/using-the-database/index.html
2. Open with Xcode 8

![screen shot 2016-10-11 at 9 10 52 pm](https://cloud.githubusercontent.com/assets/1365736/19297194/4461ed5c-8ff7-11e6-94f9-5b23028a8aaf.png)

**Comment by sethrosetter** [comment]
Not seeing this on master

**Comment by jamiltz** [comment]
Yeah master is reflected on the developer-qa link but not live yet. Can't deploy it because there are some redirects that need to be added. So unfortunately it brakes for Swift 3. [Added](https://github.com/couchbaselabs/couchbase-mobile-portal/commit/7c8a2bbc00ada86192dcc7a569f676f32d051cf0) a requirements section on the training page to advise readers it's compatible for Swift 2 only at the moment.
