### ISSUE TITLE
Any doc deleted from CBS server doesn't get deleted at CBL side

### ISSUE THREAD

**Issue by hrajput89** [couchbaselabs/mobile-training-todo#168]
1. Deploy a todo app for 1.4 with SG 1.5.1-4 and CBS 5.0.0-3519. 
2, Create few docs such as couple of List docs and couple of Task docs.
3. Verify that docs are getting synced to CBS.
4. Delete a List and Task Doc and check that doc is also getting deleted at CBL App. - Failed

[running_server_config.log](https://github.com/couchbaselabs/mobile-training-todo/files/1614456/running_server_config.log)
[sync_gateway_access.log](https://github.com/couchbaselabs/mobile-training-todo/files/1614457/sync_gateway_access.log)
[sync_gateway_error.log](https://github.com/couchbaselabs/mobile-training-todo/files/1614458/sync_gateway_error.log)

[sync_gateway.log](https://github.com/couchbaselabs/mobile-training-todo/files/1614459/sync_gateway.log)

[TODO CBL App Logs.log](https://github.com/couchbaselabs/mobile-training-todo/files/1614482/TODO.CBL.App.Logs.log)

**Comment by raghusarangapani** [comment]
Can you retry with the xattrs configs enabled in SG config?
```
"enable_shared_bucket_access": true,
"import_docs": "continuous",
```

**Comment by adamcfraser** [comment]
When an SDK change is imported, oldDoc will always be undefined (since the previous doc body is no longer available).

In the delete case, the sync function still ends up calling getType(), which does:
    `return (isDelete() ? oldDoc.type : doc.type);`

When oldDoc is undefined, this is going to throw the TypeError seen in the SG logs.

The Sync Function needs to be modified to handle oldDoc=nil in all relevant scenarios.

Generally speaking I think we need to improve our docs around this fact (olddoc=nil on import) - I'll file a ticket for that.
