### ISSUE TITLE
.NET: List deletion not propagating from iOS to .NET

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-training-todo#29]
Possibly related to #28 

Steps to reproduce

1. Create share a list from iOS -> .NET
2. Delete the list on iOS
3. Deletion does not update the .NET Lists view

**Comment by borrrden** [comment]
I am seeing sync exceptions when pushing deletes from iOS.  Do you see those too?

> CBLRestPusher[http://10.17.6.34:4984/todo/]: _bulk_docs got an error: {
    error = 500;
    id = "-MEwM9pVtakedD4uLXDMZNg";
    reason = "Exception in JS sync function";
    status = 500;
} {at __40-[CBLRestPusher uploadBulkDocs:changes:]_block_invoke:402}

**Comment by jamiltz** [comment]
@borrrden can you try again with the config file on master?
There was an issue related to syncing that got fixed. This one here only happened iOS -> .NET and not iOS -> iOS.

**Comment by jamiltz** [comment]
It's possibly the same as https://github.com/couchbaselabs/mobile-training-todo/issues/28

**Comment by borrrden** [comment]
I already fixed #28, but this problem is still persisting.  I see that task LISTS were fixed for this but what about tasks themselves?  I am already using the latest master version of the config file.

**Comment by borrrden** [comment]
The 500 was a fluke...it doesnt happen anymore and deletes propagate normally.

**Comment by jamiltz** [comment]
Fixed

**Comment by sethrosetter** [comment]
Still an issue

**Comment by jamiltz** [comment]
Need to retest in test fest.

**Comment by borrrden** [comment]
I apparently missed or forgot about the discussion that was had about active_only and web sockets.  If you make an active_only request on web sockets, it will stay active only forever and deletes will never sync.  The reason this didn't always happen is because active_only will only be triggered on a new (from 0) replication with an empty local DB.  This was a .NET issue, though I'm not sure if iOS has the same logic in place to handle this (@pasin seems to think so but I couldn't confirm).

The fix was to tear down and start a new active_only=false web socket connection if an active_only=true connection receives a "caught up" signal.
